# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_rate_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='dailyValue',
            new_name='daily_value',
        ),
    ]
