# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20161218_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rate',
            name='daily_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rate',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='value_currency',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='daily_value_currency',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='value_currency',
        ),
    ]
